config/routes.rb
Rails.application.routes.draw do
  get 'follow/follow_user'
  post 'follow/follow_user'

  root 'home#index'

  get 'home/index'
  get 'home/about'

  get 'follow/users'
  get 'api/users'
  

  resources :posts

  devise_for :users
  resources :users

  
  

end

app/models/follow.rb
 class Follow < ActiveRecord::Base
       #has_many :users, :foreign_key => "follows_id"
       #has_many :users, :foreign_key => "target_id"

       belongs_to :follower, :class_name => "User"
       belongs_to :target, :class_name => "User"

        validates_uniqueness_of :follower_id, :scope => [:target_id]
 end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  belongs_to :follows

  has_many :how_follows, :class_name => 'Follows', :foreign_key => 'follower_id'
  has_many :i_am_following, :class_name => 'Follows', :foreign_key => 'target_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  	def follow(target_user)

	  	response = Follow.where(:follower_id => self.id).where(:target_id => target_user.id)

	  	msg = {}

		if response.empty?
		 	@follow = Follow.new
		  	@follow.follower_id = self.id 
		  	@follow.target_id = target_user.id
		  	if @follow.save
				msg[:feedback] = 'Você está agora seguindo este usuário'
				msg[:button] = 'UnFollow'
			end
		else
			response[0].destroy
			msg[:feedback] = 'Você deixou de seguir este usuário'
			msg[:button] = 'Follow'
		end

		json = msg.to_json
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :null_session
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
 
  before_filter :authenticate_user!
	
  def follow_user 

    target_user = User.find(params[:follow_target])

	  json = current_user.follow(target_user)
	
	  respond_to do |format|
      format.json {render :json => json}
    end		
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:user_id => current_user.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /users
  # GET /users.json
  def index
    @users = User.where.not(:id => current_user.id )
    @messages = 'asdasdasd'
    respond_to do |format|
      format.json {render :json => @users}
      format.html{ render :index => @users}
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @posts = Post.where(:user_id => params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_following()
		@follow = Follow.where(:follower_id => current_user.id)
	end

	def get_followers()
		@follow = Follow.where(:target_id => current_user.id)
	end
end

app/helpers/follow_helper.rb
module FollowHelper
	def am_i_following(user)
		if user.id
			response = Follow.where(:follower_id => current_user.id).where(:target_id => user.id)

			if response.empty? 
				return 'Follow'
			end
				return 'UnFollow'			
		end	
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def is_post_owner?(post)
		post.user_id == current_user.id
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>About</h1>
<p>This is a twitter like blog</p>

app/views/home/new.html.erb
<h1>Home#new</h1>
<p>Find me in app/views/home/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="myApp">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HEmicroblog" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <style type="text/css">

      #container{
        padding: 1em;
      }

      .url{
        border: 1px solid gray;
        margin-bottom:1em;
      }

      #title{}

      .url .title {
        color: #534540;
        font-size:2em;
        text-decoration: underline;
      }

      .url:hover{
        background: #fcf5e2;
      }

      .url a {
           text-decoration: none;
           display: block;
           width: 100%;
           height: 100%;
      }
      .description{
        color: #999999;
        font-size: 17px;
        margin: 5px 0 0 12px;
        display: block;
        word-break:break-all;
      }
      .user-image-holder img{
        display:inline-block;
      }

      .project-avatar{
        margin:20px;
        border: 1px solid black;
      }

      .comment-holder{
        position:relative;
        display:inline-block;
        margin-top:12px;
      }

      .comment-counter{
        position:absolute;
        top: 1px;
        right: 10px;
        font-size: 14px;
      }

      .comment-ballon:hover{
        cursor:pointer;
      }

      header{
        width:100%;
        background-color:red;
        margin-bottom: 2em;
      }

      header .row{
        padding: 31px;
      }

      #header-links{
        margin-top:1em;
        
      }

      .button {
        background-color: white !important;
        color:black;
      }

      .button:hover{
        color:red;
      }

      .notification-div{
        width: 60%;;
        float: right;
      }
        .inner-notification-div{
          width: 100%;
          height: 100px;
          background-color: #fff;
          overflow-y: scroll;
        }

        .notification-div li {
          list-style-type: none !important;
        }
    </style>
  </head>

  <body>
    <header>
      <div class="row">
        <div class="large-10" style="display:inline-block">
          <ul id="header-links" class="inline-list right">
            <% if user_signed_in? %>
            <li>
            <%= link_to("Logout (#{current_user.email})", destroy_user_session_path, :method => :delete, :class=>"button radius small") %>        
            </li>
             <li>
            <%= link_to('My Posts',{:controller => 'posts', :action => 'index', :id => current_user.id }, :class=>'button radius small') %>
            </li>
            <li>
            <%= link_to('Users',{:controller => 'users', :action => 'index'}, :class=>'button radius small') %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path,:class=>"button radius small")  %>
            </li>
          <% end %>
             <li>
            <%= link_to('About',{:controller => '/home', :action => 'about'}, :class=>'button radius small') %>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="columns large-2">
          <h1 id="title" style="display:inline-block">HEmicroblog</h1>
        </div>
        <div class="columns large-10">
            <% if user_signed_in? %> 

            <div class="notification-div">
               <p >Notificações:</p>
              <div class="inner-notification-div">
               <ul>
                <% get_followers().each do |follow| %>
                  <li><%= follow.follower.email %> passou a seguir você</li>
                <% end %>
              </ul>
              </div>            
            </div>   
           <% end %>
        </div>         
        </div>
      </div>
    </header>
    <div id="container">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Id user:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<% if is_post_owner?(@post) %>
	<%= link_to 'Edit', edit_post_path(@post) %> 
<% end %>

<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div ng-controller="myCtrl">

  <h1>Listing users</h1>

  <h3 style="text-align:center;">Search User</h3>
  <form class="form-inline">
    <input ng-model="query" type="text" placeholder="Filter by name" autofocus>
  </form>


  <ul ng-repeat="user in users | filter: query | orderBy: 'email' ">
    <li style="list-style-type:none"><a href="/users/{{user.id}}">{{user.email}}</a></li>
  </ul>

  <br>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<style>
  .successfully-saved {
    -webkit-transition: opacity 3s ease-in-out;
    -moz-transition: opacity 3s ease-in-out;
    -ms-transition: opacity 3s ease-in-out;
    -o-transition: opacity 3s ease-in-out;
     opacity: 0;
  }
</style>
<div ng-controller="userShowCtrl" style="margin-left: auto;margin-right: auto;width: 50%;">
  <p id="notice" ng-model="notice" ng-init="notice='<%= notice %>'">{{notice}}</p>
  <div>
    <h1 style="display:inline-block"><%= @user.email %></h1>        
     <a id="<%= @user.id %>" ng-value="<%= am_i_following(@user) %>" class="follow" ng-click="follow($event)" href=""><%= am_i_following(@user) %></a>
  </div>
  </br>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post %></td>
          <td><%= post.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>